# Generated by Django 4.2.7 on 2023-11-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='edu_sys.lesson'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='edu_sys.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='edu_sys.subject'),
        ),
    ]
